name: rxnova_clinical_ai
description: Offline voice-driven OPD clinical documentation and decision support app.
publish_to: 'none'
version: 0.2.0+2

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  intl: ^0.19.0
  path: ^1.9.0
  path_provider: ^2.1.4
  pdf: ^3.11.3
  sqflite_common_ffi: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true
